name: test-slack-send

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-slack-send.yml'
      - 'slack/send/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-slack-send.yml'
      - 'slack/send/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./slack/send
        id: slack-send
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          message: "Run something"

      - name: validate thread-timestamp
        run: test -n "${{ steps.slack-send.outputs.thread-timestamp }}"

      - uses: ./slack/send
        id: slack-reply
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          message: "Run something else"
          thread-timestamp: ${{ steps.slack-send.outputs.thread-timestamp || '' }}

      - name: validate thread-timestamp
        run: test -n "${{ steps.slack-reply.outputs.thread-timestamp }}"

      - uses: ./slack/send
        id: slack-multi
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          thread-timestamp: ${{ steps.slack-send.outputs.thread-timestamp || '' }}
          message: |
            :warning: I couldn't find a person for `foo` in the <${{ github.event.repository.html_url }}/blob/master/.github/config.json|config.json file>.
            Make sure to update the `config.json` file or the schedule for `bar`!

            Test some characters: & and * and < > \n \r

            Failed to assign <${{ github.event.repository.html_url }}|SDH #my-issue>.

      - uses: ./slack/send
        id: slack-debug
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          thread-timestamp: ${{ steps.slack-send.outputs.thread-timestamp || '' }}
          message: |
            :traffic_cone: `reusable-sdh-assignment` failed for `${{ github.repository }}@${{ github.ref_name }}`, @robots-ci please look what's going on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>.
            You can access the <https://github.com/elastic/app-obs-dev/blob/main/sdh-assignment/TROUBLESHOOTING.md|Runbook> for helping out with the troubleshooting.
